### ISSUE TITLE
Can't bypass https://nowsecure.in/

### ISSUE THREAD

**Issue by aaronpeng2020** [Kaliiiiiiiiii-Vinyzu/patchright-python#1]
```import asyncio
import os
from patchright.async_api import async_playwright

async def main():
    user_data_dir = os.path.join(os.getcwd(), "chrome_user_data")
    
    os.makedirs(user_data_dir, exist_ok=True)
    
    async with async_playwright() as p:
        context = await p.chromium.launch_persistent_context(
            user_data_dir=user_data_dir,  
            channel="chrome",
            headless=False,
            no_viewport=True,
            args=['--no-sandbox']  
        )
        page = await context.new_page()
        await page.goto('https://nowsecure.in/')
        await page.wait_for_load_state('networkidle')
        await page.wait_for_load_state('load')
        title = await page.title()
        print(title)
        for i in range(1000):
            title = await page.title()
            print(title)
            if title == 'Just a moment...':
                await asyncio.sleep(1)
                continue
            else:
                break
        await page.screenshot(path=f'example-{p.chromium.name}.png')
        await context.close()

asyncio.run(main())
```

I need to click the checkbox, but I'm unable to locate the iframe

```
iframe = page.frame_locator('#shadow-root iframe[id^="cf-chl-widget"]')
print(iframe)
```

```
<FrameLocator frame=<Frame name= url='https://nowsecure.in/'> selector='#shadow-root iframe[id^="cf-chl-widget"]'>
Traceback (most recent call last):
  File "e:\dev2024\patchright\async.py", line 50, in <module>
    asyncio.run(main())
  File "E:\Users\Administrator\anaconda3\envs\patchright\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\Users\Administrator\anaconda3\envs\patchright\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "e:\dev2024\patchright\async.py", line 40, in main
    content = await frame.content()
AttributeError: 'FrameLocator' object has no attribute 'content'
```

**Comment by Vinyzu** [comment]
You have a [FrameLocator](https://playwright.dev/python/docs/api/class-framelocator#frame-locator-locator), what you want is [Frame.content](https://playwright.dev/python/docs/api/class-frame#frame-content).

**Comment by aaronpeng2020** [comment]
```
Just a moment...
Just a moment...
<FrameLocator frame=<Frame name= url='https://nowsecure.in/'> selector='#shadow-root iframe[id^="cf-chl-widget"]'>
Traceback (most recent call last):
  File "e:\dev2024\patchright\async.py", line 55, in <module>
    asyncio.run(main())
  File "E:\Users\Administrator\anaconda3\envs\patchright\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\Users\Administrator\anaconda3\envs\patchright\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "e:\dev2024\patchright\async.py", line 43, in main
    context = iframe.context
AttributeError: 'FrameLocator' object has no attribute 'context'
```

**Comment by aaronpeng2020** [comment]
```
Just a moment...
Just a moment...
<FrameLocator frame=<Frame name= url='https://nowsecure.in/'> selector='#shadow-root iframe[id^="cf-chl-widget"]'>
Traceback (most recent call last):
  File "e:\dev2024\patchright\async.py", line 55, in <module>
    asyncio.run(main())
  File "E:\Users\Administrator\anaconda3\envs\patchright\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\Users\Administrator\anaconda3\envs\patchright\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "e:\dev2024\patchright\async.py", line 43, in main
    context = iframe.context()
AttributeError: 'FrameLocator' object has no attribute 'context'
```

**Comment by aaronpeng2020** [comment]
What I mean is that you cannot bypass it without clicking the checkbox

**Comment by aaronpeng2020** [comment]
frame.context is a other question

**Comment by Vinyzu** [comment]
You regulary cant bypass cloudflare without clicking the checkbox.
Youre implementation for clicking is wrong, which is why you got the exception.

There is nothing wrong with patchright in this case.
